// Templates de currículo baseados nos PDFs enviados pelo usuário

export const TEMPLATES = [
  {
    id: 'turquoise_medical',
    name: 'Turquesa Profissional',
    description: 'Sidebar turquesa com foto, checkmarks e detalhes modernos',
    preview_color: '#4DC8C8',
    category: 'Moderno',
    isNew: true,
  },
  {
    id: 'sales_gray',
    name: 'Cinza Vendas',
    description: 'Foto circular, sidebar cinza claro, referências e seções limpas',
    preview_color: '#8A9BB0',
    category: 'Corporativo',
    isNew: true,
  },
  {
    id: 'dark_navy_cover',
    name: 'Navy Escuro',
    description: 'Sidebar dark navy com foto circular, ícones de contato elegantes',
    preview_color: '#2D3748',
    category: 'Executivo',
    isNew: true,
  },
  {
    id: 'magenta_minimal',
    name: 'Magenta Minimalista',
    description: 'Linha vertical magenta, contato com ícones, habilidades em bullets',
    preview_color: '#9B2163',
    category: 'Minimalista',
    isNew: true,
  },
  {
    id: 'gray_photo_classic',
    name: 'Clássico com Foto',
    description: 'Sidebar cinza com foto, triângulos como bullets, estilo clássico',
    preview_color: '#6B7280',
    category: 'Clássico',
    isNew: true,
  },
  {
    id: 'engineering_cream_blue',
    name: 'Engenharia Creme/Azul',
    description: 'Nome grande no header, 2 colunas, azul navy elegante',
    preview_color: '#2B4F9E',
    category: 'Corporativo',
    isNew: true,
  },
  {
    id: 'industrial_gray',
    name: 'Industrial Cinza',
    description: 'Sidebar cinza escuro com foto, formato europeu/espanhol',
    preview_color: '#4B5563',
    category: 'Moderno',
    isNew: true,
  },
  {
    id: 'bw_labeled',
    name: 'P&B com Labels',
    description: 'Totalmente branco, nome grande, labels à esquerda em negrito',
    preview_color: '#1F2937',
    category: 'Minimalista',
    isNew: true,
  },
  {
    id: 'beige_education',
    name: 'Educação Bege',
    description: 'Fundo bege suave, foto redonda, seções com bordas à esquerda',
    preview_color: '#92654E',
    category: 'Clássico',
    isNew: true,
  },
  {
    id: 'systems_blue',
    name: 'Sistemas Azul Royal',
    description: '2 colunas, títulos em azul brilhante, nome em bold grande',
    preview_color: '#4169E1',
    category: 'Tecnologia',
    isNew: true,
  },
  // Templates clássicos mantidos
  {
    id: 'classic_blue',
    name: 'Clássico Azul',
    description: 'Elegante e tradicional, ideal para cargos corporativos',
    preview_color: '#1D4371',
    category: 'Corporativo',
  },
  {
    id: 'modern_dark',
    name: 'Moderno Escuro',
    description: 'Sofisticado com coluna lateral escura',
    preview_color: '#1a1a2e',
    category: 'Moderno',
  },
  {
    id: 'executive',
    name: 'Executivo',
    description: 'Premium com cabeçalho em gradiente para cargos de liderança',
    preview_color: '#2c3e50',
    category: 'Executivo',
  },
  {
    id: 'minimal_gray',
    name: 'Minimal Cinza',
    description: 'Ultra minimalista, foco total no conteúdo',
    preview_color: '#555555',
    category: 'Minimalista',
  },
  {
    id: 'clean_green',
    name: 'Limpo Verde',
    description: 'Minimalista com toques verdes, perfeito para área de saúde',
    preview_color: '#057642',
    category: 'Moderno',
  },
  {
    id: 'tech_dark',
    name: 'Tech Dark',
    description: 'Ideal para desenvolvedores e profissionais de TI',
    preview_color: '#0d1117',
    category: 'Tecnologia',
  },
];

export const CATEGORIES = ['Todos', '🆕 Novos', 'Corporativo', 'Moderno', 'Minimalista', 'Executivo', 'Clássico', 'Tecnologia'];