// 21 templates profissionais de currículo

export const TEMPLATES = [
  // ── Originais ──────────────────────────────────────────────────────────
  {
    id: 'classic_blue',
    name: 'Clássico Azul',
    description: 'Elegante e tradicional, ideal para cargos corporativos',
    preview_color: '#1D4371',
    category: 'Corporativo',
  },
  {
    id: 'modern_dark',
    name: 'Moderno Escuro',
    description: 'Sofisticado com coluna lateral escura',
    preview_color: '#1a1a2e',
    category: 'Moderno',
  },
  {
    id: 'clean_green',
    name: 'Limpo Verde',
    description: 'Minimalista com toques verdes, perfeito para área de saúde',
    preview_color: '#057642',
    category: 'Minimalista',
  },
  {
    id: 'executive',
    name: 'Executivo',
    description: 'Premium com cabeçalho em gradiente para cargos de liderança',
    preview_color: '#2c3e50',
    category: 'Executivo',
  },
  {
    id: 'creative_purple',
    name: 'Criativo Roxo',
    description: 'Destaque para profissionais criativos e de design',
    preview_color: '#6c3483',
    category: 'Criativo',
  },
  {
    id: 'tech_dark',
    name: 'Tech Dark',
    description: 'Ideal para desenvolvedores e profissionais de TI',
    preview_color: '#0d1117',
    category: 'Tecnologia',
  },
  {
    id: 'elegant_red',
    name: 'Elegante Vermelho',
    description: 'Impactante com detalhes em vermelho para se destacar',
    preview_color: '#c0392b',
    category: 'Corporativo',
  },
  {
    id: 'minimal_gray',
    name: 'Minimal Cinza',
    description: 'Ultra minimalista, foco total no conteúdo',
    preview_color: '#555555',
    category: 'Minimalista',
  },
  {
    id: 'teal_modern',
    name: 'Teal Moderno',
    description: 'Coluna lateral com foto de destaque',
    preview_color: '#0d7377',
    category: 'Moderno',
  },
  {
    id: 'orange_accent',
    name: 'Laranja Accent',
    description: 'Energético com acentos em laranja, ideal para vendas',
    preview_color: '#e67e22',
    category: 'Criativo',
  },
  {
    id: 'navy_professional',
    name: 'Navy Profissional',
    description: 'Azul marinho clássico com linha dividida',
    preview_color: '#003153',
    category: 'Executivo',
  },
  {
    id: 'fresh_light',
    name: 'Fresco Claro',
    description: 'Layout claro e arejado para recém-formados',
    preview_color: '#3498db',
    category: 'Minimalista',
  },
  {
    id: 'bold_black',
    name: 'Bold Black',
    description: 'Ousado e marcante com tipografia forte',
    preview_color: '#222222',
    category: 'Moderno',
  },
  {
    id: 'pink_creative',
    name: 'Rosa Criativo',
    description: 'Feminino e elegante para áreas criativas',
    preview_color: '#ad1457',
    category: 'Criativo',
  },
  {
    id: 'golden_executive',
    name: 'Dourado Executivo',
    description: 'Luxuoso com detalhes dourados para cargos executivos',
    preview_color: '#b7950b',
    category: 'Executivo',
  },
  // ── Novos Templates (inspirados nos modelos enviados) ──────────────────
  {
    id: 'bw_infographic',
    name: 'Preto & Branco Infográfico',
    description: 'Limpo e profissional, seções em destaque cinza arredondado',
    preview_color: '#333333',
    category: 'Novos',
    isNew: true,
  },
  {
    id: 'beige_brown',
    name: 'Bege & Marrom Clássico',
    description: 'Elegante com foto, layout duas colunas em tom quentinho',
    preview_color: '#7B3F00',
    category: 'Novos',
    isNew: true,
  },
  {
    id: 'blue_gray_pro',
    name: 'Azul Cinza Profissional',
    description: 'Header navy, sidebar lateral com timeline de experiência',
    preview_color: '#1D2B4F',
    category: 'Novos',
    isNew: true,
  },
  {
    id: 'blue_photo_sidebar',
    name: 'Azul com Foto Lateral',
    description: 'Sidebar azul escuro com foto no topo e dados à direita',
    preview_color: '#1B4F8A',
    category: 'Novos',
    isNew: true,
  },
  {
    id: 'beige_soft_photo',
    name: 'Bege Suave com Foto',
    description: 'Fundo bege claro, foto circular e barras de habilidades',
    preview_color: '#8B7355',
    category: 'Novos',
    isNew: true,
  },
  {
    id: 'dark_sidebar_cv',
    name: 'CV Sidebar Escuro',
    description: 'Sidebar escuro elegante com foto circular e conteúdo branco',
    preview_color: '#2B3444',
    category: 'Novos',
    isNew: true,
  },
];

export const CATEGORIES = ['Todos', 'Corporativo', 'Moderno', 'Minimalista', 'Executivo', 'Criativo', 'Tecnologia'];